### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ashwarhussain** [icebeam7/MobileClassifierDemo#1]
Hello @icebeam7,

youtube video at https://www.youtube.com/watch?v=4oKcLkfYLUo has brought me here. Very nice demo and total end to end. lovely :)

need your help in running this project. When I am debugging this project on my Visual Studio 2019 I am getting the below error. Can you please have a look and also help me on how to run this project and execute the image classification model.

Error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to generate Java type for class: Android.Support.V4.View.Accessibility.AccessibilityManagerCompat/IAccessibilityStateChangeListenerImplementor due to MAX_PATH: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Code\ML\Deep Learning\MobileClassifierDemo-master\MobileClassifierDemo-master\MobileClassifierDemo\MobileClassifierDemo.Android\obj\Debug\90\android\src\mono\android\support\v4\view\accessibility\AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.java'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.Android.Build.Tasks.Files.CopyIfStreamChanged(Stream stream, String destination) in /Users/builder/azdo/_work/2/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 170
   at Xamarin.Android.Tasks.GenerateJavaStubs.CreateJavaSources(IEnumerable`1 javaTypes, TypeDefinitionCache cache)	MobileClassifierDemo.Android

**Comment by ashwarhussain** [comment]
hello @icebeam7 

changed the path and build error is resolved now. BUT the app is not getting loaded on the android Emulator. Any idea?
